### ISSUE TITLE
成功安装，但N卡+A卡使用有问题，求教一下

### ISSUE THREAD

**Issue by wintry** [KTGWKenta/Hackintosh-Asus-Z370a#2]
n卡和a卡都接了显示器，配置里也删了禁用独显的选项，
但进系统前无输出，导致开机不能选系统
且输出好像是n卡在输出（昨天安装很晚了，没记清楚）
单独接a卡，一切正常

求助需要修改什么设置，或者给个关键词我自己去搜索

**Comment by KTGWKenta** [comment]
抱歉，我没有这么搞的过，没啥头绪。不过10.13以上的系统不支持N卡(除了很老的那几款)，我猜测可能得写DSDT屏蔽你的N卡。
